# This default may be swapped for any compatible base image
ARG BASE_IMAGE=ubuntu:24.04

# Containerbase is used for tool installation and user/directory setup
FROM ghcr.io/containerbase/base:13.23.10 AS containerbase

FROM ${BASE_IMAGE} as base

RUN apt-get update -y && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*

# Containerbase supports custom user
ARG USER_NAME=wss-scanner
ARG USER_ID=1000
ARG USER_HOME=/home/${USER_NAME}
ARG APT_HTTP_PROXY

# Set env and shell
ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

# Set up containerbase
COPY --from=containerbase /usr/local/sbin/ /usr/local/sbin/
COPY --from=containerbase /usr/local/containerbase/ /usr/local/containerbase/
RUN install-containerbase && \
    prepare-tool all

# renovate: datasource=github-tags depName=git lookupName=git/git
ARG GIT_VERSION=v2.41.3
RUN install-tool git

# install git lfs
#ARG GIT_LFS_VERSION=v3.5.1
#RUN install-tool git-lfs

# renovate: datasource=docker depName=node versioning=docker
ARG NODE_VERSION=24.0.0
RUN install-tool node

# renovate: datasource=npm depName=npm versioning=npm
ARG NPM_VERSION=11.6.1
RUN install-tool npm

# renovate: datasource=npm depName=yarn
ARG YARN_VERSION=1.22.22
RUN install-tool yarn

# renovate: datasource=npm depName=bower
ARG BOWER_VERSION=1.8.14
RUN install-tool bower
# ┌────────────┬────────────┬────────────────────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                                               │
# ├────────────┼────────────┼────────────────────────────────────────────────────────────────────┤
# │ Critical   │ 11         │ CVE-2023-26136, CVE-2019-10744, CVE-2021-23807, CVE-2025-7783      │
# │            │            │ CVE-2023-26136, CVE-2019-10744, CVE-2025-7783, CVE-2021-23383      │
# │            │            │ CVE-2021-3918, CVE-2021-23369, CVE-2021-44906                      │
# ├────────────┼────────────┼────────────────────────────────────────────────────────────────────┤
# │ High       │ 28         │ CVE-2022-24999, CVE-2022-3517, CVE-2020-8116, CVE-2020-8203        │
# │            │            │ CVE-2021-23337, CVE-2021-23343, CVE-2020-36604, CVE-2018-3728      │
# │            │            │ CVE-2022-3517, CVE-2016-10540, CVE-2022-25883, CVE-2015-8855       │
# │            │            │ CVE-2022-25883, CVE-2020-8203, CVE-2021-23337, CVE-2017-15010      │
# │            │            │ CVE-2017-15010, CVE-2024-12905, CVE-2025-48387, CVE-2025-59343     │
# │            │            │ CVE-2022-24999, CVE-2017-1000048, CVE-2022-21213, CVE-2020-7792    │
# │            │            │ CVE-2021-43138, CVE-2022-29167, CVE-2022-21213, CVE-2020-7792      │
# └────────────┴────────────┴────────────────────────────────────────────────────────────────────┘

ARG PNPM_VERSION=10.17.0
RUN install-tool pnpm

### provide permissions
RUN echo '{ "allow_root": true }' > ${USER_HOME}/.bowerrc && \
	chown -R ${USER_NAME}:${GROUP_NAME} ${USER_HOME}/.bowerrc

ARG JAVA_VERSION=8.0.432+6
RUN install-tool java

ARG JAVA_VERSION=11.0.25+9
RUN install-tool java

ARG JAVA_VERSION=21.0.5+11.0.LTS
RUN install-tool java

### !!! PAY ATTENTION! The version that should be the default, must be installed last !!! ###
ARG JAVA_VERSION=17.0.13+11
RUN install-tool java
ENV MEND_JAVA=/usr/local/bin/mend_java
RUN ln -sf /opt/containerbase/tools/java/$JAVA_VERSION/bin/java $MEND_JAVA && \
    chmod +x $MEND_JAVA

# renovate: datasource=gradle-version depName=gradle versioning=gradle
ARG GRADLE_VERSION=6.9.4
RUN install-tool gradle
# ┌────────────┬────────────┬───────────────────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                                              │
# ├────────────┼────────────┼───────────────────────────────────────────────────────────────────┤
# │ Critical   │ 5          │ CVE-2025-4949, CVE-2021-26291, CVE-2021-26291, CVE-2022-1471      │
# │            │            │ CVE-2020-7692                                                     │
# ├────────────┼────────────┼───────────────────────────────────────────────────────────────────┤
# │ High       │ 18         │ CVE-2021-46877, CVE-2020-36518, CVE-2022-42003, CVE-2022-42004    │
# │            │            │ CVE-2022-46751, CVE-2022-37866, CVE-2022-25647, CVE-2023-2976     │
# │            │            │ CVE-2021-36090, CVE-2024-21634, CVE-2024-47554, CVE-2025-52999    │
# │            │            │ CVE-2022-25857, CVE-2021-35516, CVE-2021-35515, CVE-2021-35517    │
# │            │            │ CVE-2021-22573, CVE-2023-4759                                     │
# └────────────┴────────────┴───────────────────────────────────────────────────────────────────┘

# renovate: datasource=gradle-version depName=gradle versioning=gradle
ARG GRADLE_VERSION=7.6.4
RUN install-tool gradle
# ┌────────────┬────────────┬────────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                               │
# ├────────────┼────────────┼────────────────────────────────────────────────────┤
# │ Critical   │ 1          │ CVE-2025-4949                                      │
# └────────────┴────────────┴────────────────────────────────────────────────────┘

# renovate: datasource=gradle-version depName=gradle versioning=gradle
ARG GRADLE_VERSION=9.1.0
RUN install-tool gradle

### !!! PAY ATTENTION! The version that should be the default, must be installed last !!! ###
# renovate: datasource=gradle-version depName=gradle versioning=gradle
ARG GRADLE_VERSION=8.14.3
RUN install-tool gradle
# ┌────────────┬────────────┬────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                               │
# ├────────────┼────────────┼────────────────────────────────────────────────────┤
# │ Critical   │ 1          │ CVE-2025-4949                                      │
# └────────────┴────────────┴────────────────────────────────────────────────────┘

# renovate: datasource=docker depName=golang versioning=docker
ARG GOLANG_VERSION=1.24.7
RUN install-tool golang
# A temporary workaround, until it is fixed by renovate
ENV GOSUMDB="sum.golang.org"

USER ${USER_ID}
## Install package managers

RUN go install github.com/tools/godep@latest && \
    go install github.com/LK4D4/vndr@latest && \
    go install  github.com/kardianos/govendor@latest

#All Deparacted/archived go package managers
# RUN go install  github.com/gpmgo/gopm@latest && \
#     go install  github.com/golang/dep/cmd/dep@latest && \
#     go install github.com/Masterminds/glide@latest && \
#     curl https://glide.sh/get | sh
USER 0

# renovate: datasource=maven depName=maven lookupName=org.apache.maven:maven
ARG MAVEN_VERSION=3.9.11
RUN install-tool maven

# renovate: datasource=github-releases depName=scala lookupName=scala/scala
ARG SCALA_VERSION=v2.13.16
RUN install-tool scala

# renovate: datasource=github-releases depName=sbt lookupName=sbt/sbt
ARG SBT_VERSION=1.5.8
RUN install-tool sbt

# renovate: datasource=github-releases depName=python lookupName=containerbase/python-prebuild
ARG PYTHON_VERSION=3.6.15
RUN install-tool python
# ┌────────────┬────────────┬────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                               │
# ├────────────┼────────────┼────────────────────────────────────────────────────┤
# │ High       │ 3          │ CVE-2024-6345, CVE-2024-53899, CVE-2025-47273      │
# └────────────┴────────────┴────────────────────────────────────────────────────┘

# renovate: datasource=github-releases depName=python lookupName=containerbase/python-prebuild
ARG PYTHON_VERSION=2.7.18
RUN install-tool python
# ┌────────────┬────────────┬────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                               │
# ├────────────┼────────────┼────────────────────────────────────────────────────┤
# │ High       │ 3          │ CVE-2024-53899, CVE-2024-6345, CVE-2025-47273      │
# └────────────┴────────────┴────────────────────────────────────────────────────┘

# renovate: datasource=github-releases depName=python lookupName=containerbase/python-prebuild
ARG PYTHON_VERSION=3.11.13
RUN install-tool python
# ┌────────────┬────────────┬────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                               │
# ├────────────┼────────────┼────────────────────────────────────────────────────┤
# │ High       │ 2          │ CVE-2024-6345, CVE-2025-47273                      │
# └────────────┴────────────┴────────────────────────────────────────────────────┘

# renovate: datasource=github-releases depName=python lookupName=containerbase/python-prebuild
ARG PYTHON_VERSION=3.12.9
RUN install-tool python

# renovate: datasource=github-releases depName=python lookupName=containerbase/python-prebuild
ARG PYTHON_VERSION=3.10.18
RUN install-tool python
# ┌────────────┬────────────┬────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                               │
# ├────────────┼────────────┼────────────────────────────────────────────────────┤
# │ High       │ 2          │ CVE-2024-6345, CVE-2025-47273                      │
# └────────────┴────────────┴────────────────────────────────────────────────────┘

# renovate: datasource=github-releases depName=python lookupName=containerbase/python-prebuild
ARG PYTHON_VERSION=3.7.17
RUN install-tool python
# ┌────────────┬────────────┬────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                               │
# ├────────────┼────────────┼────────────────────────────────────────────────────┤
# │ High       │ 2          │ CVE-2024-6345, CVE-2025-47273                      │
# └────────────┴────────────┴────────────────────────────────────────────────────┘

# renovate: datasource=github-releases depName=python lookupName=containerbase/python-prebuild
ARG PYTHON_VERSION=3.8.20
RUN install-tool python
# ┌────────────┬────────────┬────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                               │
# ├────────────┼────────────┼────────────────────────────────────────────────────┤
# │ High       │ 2          │ CVE-2024-6345, CVE-2025-47273                      │
# └────────────┴────────────┴────────────────────────────────────────────────────┘

# renovate: datasource=github-releases depName=python lookupName=containerbase/python-prebuild
ARG PYTHON_VERSION=3.13.7
RUN install-tool python

# renovate: datasource=github-releases depName=python lookupName=containerbase/python-prebuild
ARG PYTHON_VERSION=3.9.21
RUN install-tool python
# ┌────────────┬────────────┬────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                               │
# ├────────────┼────────────┼────────────────────────────────────────────────────┤
# │ High       │ 2          │ CVE-2024-6345, CVE-2025-47273                      │
# └────────────┴────────────┴────────────────────────────────────────────────────┘

# renovate: datasource=pypi depName=checkov ; Must be installed after python and before python version 3.7.17
ARG CHECKOV_VERSION=3.2.471
RUN install-tool checkov
# ┌────────────┬────────────┬────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                               │
# ├────────────┼────────────┼────────────────────────────────────────────────────┤
# │ High       │ 2          │ CVE-2025-24359, GHSA-vp47-9734-prjw                │
# └────────────┴────────────┴────────────────────────────────────────────────────┘

ARG PHP_VERSION=8.4.10
RUN install-tool php

# renovate: datasource=github-releases depName=composer lookupName=composer/composer
ARG COMPOSER_VERSION=2.0.14
RUN install-tool composer

# These are needed to get earlier dotnet versions to install in Ubuntu 24.04
RUN curl -o /tmp/libssl1.1.deb https://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb && \
    dpkg -i /tmp/libssl1.1.deb
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

ARG DOTNET_VERSION=2.2.207
RUN install-tool dotnet

ARG DOTNET_VERSION=3.1.426
RUN install-tool dotnet

ARG DOTNET_VERSION=5.0.408
RUN install-tool dotnet

ARG DOTNET_VERSION=6.0.428
RUN install-tool dotnet

ARG DOTNET_VERSION=8.0.413
RUN install-tool dotnet
# ┌────────────┬────────────┬───────────────────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                                              │
# ├────────────┼────────────┼───────────────────────────────────────────────────────────────────┤
# │ High       │ 11         │ CVE-2025-26646, CVE-2025-26646, CVE-2024-38095, CVE-2025-55247    │
# │            │            │ CVE-2025-26646, CVE-2025-55247, CVE-2025-55247, CVE-2025-55247    │
# │            │            │ CVE-2025-26646, CVE-2025-55247, CVE-2025-55247                    │
# └────────────┴────────────┴───────────────────────────────────────────────────────────────────┘

ARG DOTNET_VERSION=9.0.101
RUN install-tool dotnet
# ┌────────────┬────────────┬───────────────────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                                              │
# ├────────────┼────────────┼───────────────────────────────────────────────────────────────────┤
# │ High       │ 6          │ CVE-2025-26646, CVE-2024-38095, CVE-2025-55247, CVE-2025-26646    │
# │            │            │ CVE-2025-55247, CVE-2025-55247                                    │
# └────────────┴────────────┴───────────────────────────────────────────────────────────────────┘

ARG DOTNET_VERSION=7.0.410
RUN install-tool dotnet
# ┌────────────┬────────────┬───────────────────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                                              │
# ├────────────┼────────────┼───────────────────────────────────────────────────────────────────┤
# │ Critical   │ 2          │ CVE-2024-0057, CVE-2021-24112                                     │
# ├────────────┼────────────┼───────────────────────────────────────────────────────────────────┤
# │ High       │ 12         │ CVE-2024-30105, CVE-2024-38081, CVE-2024-30105, CVE-2025-26646    │
# │            │            │ CVE-2024-30105, CVE-2025-26646, CVE-2024-30105, CVE-2024-38095    │
# │            │            │ CVE-2024-30105, CVE-2024-38095, CVE-2024-38095, CVE-2025-26646    │
# └────────────┴────────────┴───────────────────────────────────────────────────────────────────┘

# Set .NET SDK 7.0.405 as the default version
RUN echo '{ "sdk": { "version": "7.0.410" } }' > ${USER_HOME}/global.json

ARG RUST_VERSION=1.58.1
RUN install-tool rust

# pip user install (so available for all python versions)
USER ${USER_ID}

# renovate: datasource=pypi depName=pipenv
ARG PIPENV_VERSION=2023.7.23
RUN install-tool pipenv



USER 0

# renovate: datasource=pypi
ARG UV_VERSION=0.9.7
RUN install-tool uv

# renovate: datasource=pypi

ARG POETRY_VERSION=2.0.1
RUN install-tool poetry

ARG POETRY_VERSION=1.6.1
RUN install-tool poetry

ENV GEM_HOME=/tmp/containerbase/cache/.ruby
ENV GEM_PATH="${GEM_HOME}"
# renovate: datasource=github-releases depName=ruby lookupName=containerbase/ruby-prebuild
ARG RUBY_VERSION=3.2.9
RUN install-tool ruby && \
    gem install rubygems-update -v 3.3.0 && \
    gem update --system
ENV PATH="${GEM_HOME}/bin:${PATH}"

# renovate: datasource=rubygems depName=bundler versioning=ruby
ARG BUNDLER_VERSION=2.4.22
RUN install-tool bundler

ARG CONAN_VERSION=2.20.1
RUN install-tool conan

RUN install-tool erlang 24.3.3.0

RUN install-tool elixir 1.13.4

#### Install rbenv and ruby-build
### or maybe be saved to /etc/profile instead of /etc/profile.d/
# RUN git clone https://github.com/sstephenson/rbenv.git ${USER_HOME}/.rbenv; \
#	git clone https://github.com/sstephenson/ruby-build.git ${USER_HOME}/.rbenv/plugins/ruby-build; \
#	${USER_HOME}/.rbenv/plugins/ruby-build/install.sh && \
#	echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh && \
#	echo 'eval "$(rbenv init -)"' >> ${USER_HOME}/.bashrc && \
#	chown -R ${USER_NAME}:${GROUP_NAME} ${USER_HOME}/.rbenv ${USER_HOME}/.bashrc
# ENV PATH ${USER_HOME}/.rbenv/bin:$PATH

# renovate: datasource=rubygems depName=cocoapods versioning=ruby
ARG COCOAPODS_VERSION=1.16.2
RUN install-tool cocoapods && \
    adduser cocoapods
USER cocoapods
RUN pod setup
USER 0

ARG HELM_VERSION=3.19.0
RUN install-tool helm

## No renovate datasource exists yet
ARG HASKELL_GHC_VERSION=8.6.5

## No renovate datasource exists yet
ARG CABAL_VERSION=3.2

ENV DEBIAN_FRONTEND noninteractive
ENV LANGUAGE	en_US.UTF-8
ENV LANG    	en_US.UTF-8
ENV LC_ALL  	en_US.UTF-8

### Install wget, curl, unzip, gnupg, locales
RUN apt-get update && \
	apt-get -y install wget curl unzip gnupg locales && \
	locale-gen en_US.UTF-8 && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /tmp/*
# ┌────────────┬────────────┬────────────────────────────────────────────────────┐
# │ Severity   │ Count      │ CVEs                                               │
# ├────────────┼────────────┼────────────────────────────────────────────────────┤
# │ High       │ 1          │ CVE-2025-38666                                     │
# └────────────┴────────────┴────────────────────────────────────────────────────┘


#### Install Conda
## Warning: Using Anaconda's default channel may require a commercial license.
## However, the conda-forge channel is not subject to the same terms. See commented
## out settings below for an example of using conda-forge.
#
# Set conda-forge to be the default registry
# conda config --add channels conda-forge
# Use conda-forge strictly
# conda config --set channel_priority strict
RUN su - ${USER_NAME} -c "cd ${USER_HOME} && \
        mkdir -p ${USER_HOME}/miniconda3 && \
        wget https://repo.anaconda.com/miniconda/Miniconda3-py39_24.1.2-0-Linux-x86_64.sh -O ${USER_HOME}/miniconda3/miniconda.sh && \
        bash ${USER_HOME}/miniconda3/miniconda.sh -b -u -p ${USER_HOME}/miniconda3 && \
        rm -rf ${USER_HOME}/miniconda3/miniconda.sh" && \
        chgrp -R 0 ${USER_HOME}/miniconda3 && \
        chmod -R g=u ${USER_HOME}/miniconda3

RUN echo '#!/usr/bin/env bash' >> /usr/bin/conda && \
        echo 'source ${USER_HOME}/miniconda3/etc/profile.d/conda.sh' >> /usr/bin/conda && \
        echo '${USER_HOME}/miniconda3/bin/conda "$@"' >> /usr/bin/conda && \
        chmod +x /usr/bin/conda

# Upgrade cryptography package to fix CVE-2024-26130 (affects versions 38.0.0-42.0.3)
ARG CRYPTOGRAPHY_VERSION=46.0.3
RUN ${USER_HOME}/miniconda3/bin/pip install --upgrade "cryptography>=${CRYPTOGRAPHY_VERSION}"


#### Important note ###
#### uncomment for:
####    Scala
####    SBT
####    Mix/ Hex/ Erlang/ Elixir
####    dotnet/nuget cli's
RUN apt-get update && \
	apt-get install -y --force-yes build-essential software-properties-common && \
	apt-get install -y --force-yes zlib1g-dev libssl-dev libreadline-dev libyaml-dev libxml2-dev libxslt-dev && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /tmp/*

## Install PHP Plugins
RUN apt-get update && \
	apt-get install -y php-mbstring && \
	apt-get install -y php-dom && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /tmp/*


#### Install R and Packrat
# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC
# Update system and install dependencies
RUN apt-get update && apt-get install -y \
    software-properties-common \
    dirmngr \
    lsb-release \
    build-essential \
    gfortran \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libfontconfig1-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libfreetype6-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    git \
    && rm -rf /var/lib/apt/lists/*
# Add CRAN repository and install R
RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | gpg --dearmor -o /usr/share/keyrings/r-project.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/r-project.gpg] https://cloud.r-project.org/bin/linux/ubuntu noble-cran40/" | tee -a /etc/apt/sources.list.d/r-project.list && \
    apt-get update && \
    apt-get install -y r-base r-base-dev && \
    rm -rf /var/lib/apt/lists/*
# Install devtools and packrat from R
RUN R -e "install.packages(c('devtools', 'packrat'), repos='https://cloud.r-project.org/')"

#### Install Cabal
RUN apt-get update &&\
	apt-get install -y build-essential curl libffi-dev libffi8ubuntu1 libgmp-dev libgmp10 libncurses-dev && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /tmp/*

RUN su - ${USER_NAME} -c "curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh && \
	source /home/wss-scanner/.ghcup/env && \
	echo "source /home/wss-scanner/.ghcup/env" >> /home/wss-scanner/.bashrc && \
	ghcup install cabal ${CABAL_VERSION} &&\
	cabal update" && \
    chgrp -R 0 ${USER_HOME}/.cabal ${USER_HOME}/.ghcup && \
    chmod -R g=u ${USER_HOME}/.cabal ${USER_HOME}/.ghcup

#### Install Mono
# RUN apt-get update && \
#     apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
#     apt-get install -y --no-install-recommends apt-transport-https ca-certificates && \
#     echo "deb https://download.mono-project.com/repo/ubuntu bionic main" | tee /etc/apt/sources.list.d/mono-official-stable.list && \
#     apt-get update && \
#     apt-get install -y mono-devel && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/* && \
#     rm -rf /tmp/*

### Install Nuget CLI
# RUN apt-get update && \
# # 	apt-get install nuget

## Install Paket
ENV PAKET_HOME=${USER_HOME}/.dotnet/tools
ENV PATH="${PATH}:${PAKET_HOME}"
RUN dotnet tool install Paket --version 7.2.1 --tool-path ${PAKET_HOME}

## Install Bazel
# renovate: datasource=github-releases packageName=bazelbuild/bazelisk
ARG BAZELISK_VERSION=v1.27.0
RUN install-tool bazelisk

# Pre-download Bazel 6.1.1 to cache it in the image
RUN USE_BAZEL_VERSION=6.1.1 bazel version

# Set Bazel 6.1.1 as the default version
ENV USE_BAZEL_VERSION=6.1.1

# Install Swift (including SPM)
ARG SWIFT_VERSION=5.10.1
RUN install-tool swift

# delete the partially populated directory /tmp/containerbase and recreate one with full content instead
RUN rm -rf /tmp/* && containerbase-cli init tool all

# END OF BASE IMAGE


# Temporarily copying the current Dockerfile and the version scanner script to generate the installed-versions.json file.
COPY generate_versions_json.sh /usr/local/bin/generate_versions_json.sh
ARG THIS_DOCKERFILE_NAME=repo-integrations/scanner/Dockerfile.full
COPY ${THIS_DOCKERFILE_NAME} /tmp/target-dockerfile
RUN chmod +x /usr/local/bin/generate_versions_json.sh \
  && mkdir "${USER_HOME}/.mend" \
  && /usr/local/bin/generate_versions_json.sh /tmp/target-dockerfile \
     > "${USER_HOME}/.mend/installed-versions.json" \
  && rm /tmp/target-dockerfile && rm /usr/local/bin/generate_versions_json.sh 
